services:
    sherlockode_sylius_acb_menu_listener:
        class: Sherlockode\SyliusAdvancedContentPlugin\Menu\AdminMenuListener
        tags:
            - { name: kernel.event_listener, event: sylius.menu.admin.main, method: addAdminMenuItems }
    sherlockode_sylius_acb_grid_filter_page_title_filter:
        class: Sherlockode\SyliusAdvancedContentPlugin\Grid\Filter\PageTitleFilter
        tags:
            -
                name: sylius.grid_filter
                type: sherlockode_acb_page_title
                form_type: Sherlockode\SyliusAdvancedContentPlugin\Grid\Form\PageTitleType
    sherlockode_sylius_acb_grid_filter_page_status_filter:
        class: Sherlockode\SyliusAdvancedContentPlugin\Grid\Filter\PageStatusFilter
        tags:
            -
                name: sylius.grid_filter
                type: sherlockode_acb_page_status
                form_type: Sherlockode\SyliusAdvancedContentPlugin\Grid\Form\PageStatusType
