sylius_grid:
    templates:
        filter:
            sherlockode_acb_page_title: '@SherlockodeSyliusAdvancedContentPlugin/Page/Grid/Filters/pageTitle.html.twig'
            sherlockode_acb_page_status: '@SherlockodeSyliusAdvancedContentPlugin/Page/Grid/Filters/pageStatus.html.twig'
    grids:
        sherlockode_sylius_acb_admin_page:
            driver:
                name: doctrine/orm
                options:
                    class:
            sorting:
                title: asc
            fields:
                id:
                    type: string
                    label: sylius.ui.id
                    sortable: ~
                title:
                    type: twig
                    path: .
                    options:
                        template: "@SherlockodeSyliusAdvancedContentPlugin/Page/Grid/Fields/pageTitle.html.twig"
                    label: sylius.ui.title
                    sortable: pageMetas.title
                status:
                    type: twig
                    options:
                        template: "@SherlockodeSyliusAdvancedContentPlugin/Page/Grid/Fields/status.html.twig"
                    label: sylius.ui.status
                    sortable: ~
            filters:
                name:
                    type: sherlockode_acb_page_title
                status:
                    type: sherlockode_acb_page_status
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
        sherlockode_sylius_acb_admin_content:
            driver:
                name: doctrine/orm
                options:
                    class: ~
                    repository:
                        method: createListQueryBuilder
            sorting:
                name: asc
            fields:
                id:
                    type: string
                    label: sylius.ui.id
                    sortable: ~
                name:
                    type: string
                    label: sylius.ui.title
                    sortable: ~
                slug:
                    type: string
                    label: sylius.ui.slug
                    sortable: ~
            filters:
                name:
                    type: string
                    label: sylius.ui.title
                slug:
                    type: string
                    label: sylius.ui.slug
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
